theme: jekyll-theme-minimal
title: James Matuk
description: Data Scientist, <br> Epidemiology Data Center, <br> University of Pittsburgh
logo: /files/20241022_TA_James Matuk_0007.jpg
show_downloads: false
google_analytics: UA-239238149-1
