theme: jekyll-theme-minimal
title: James Matuk
description: Data Scientist, <br> Epidemiology Data Center, <br> University of Pittsburgh
logo: /files/matuk_photo.png
show_downloads: false
google_analytics: UA-239238149-1
