theme: jekyll-theme-minimal
title: James Matuk
description: Postdoctoral Associate, Department of Statistical Science, Duke University
logo: https://media-exp1.licdn.com/dms/image/C4E03AQH5stzzQgALeA/profile-displayphoto-shrink_400_400/0/1599077116194?e=1667433600&v=beta&t=tJ1ctqyW71yBFobi7-X-0ZYj7vwPBeZB4glvcOa5QNg
show_downloads: false
